---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# BSPBSS

<!-- badges: start -->
<!-- badges: end -->

Bayesian Spatial Blind Source Separation via Thresholded Gaussian Process.

## Installation

You can install the released version of nlss from Github with:

``` r
library(devtools)
install_github("benwu233/BSPBSS")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(BSPBSS)

#simulate images with a probabilistic ICA model
sim = sim_2Dimage_ICA(length = 30, sigma = 5e-4, n = 20, smooth = 0)

#generate initial values for mcmc.
ini = init_bspbss(sim$X, xgrid = sim$xgrid, q = 3,dens= 0.5,kernel="gaussian", ker_par = c(0.1,10), num_eigen = 50 )

#mcmc
res = mcmc_bspbss(sim$X,ini$init,ini$prior,ini$kernel,ep=0.5,lr = 0.1,decay = 0.1,subsample_n = 0.5, subsample_p = 0.5,n.iter = 5000,n.burn_in = 3000,thin = 10,show_step = 1000)

#summarize the result
res_sum = sum_mcmc_bspbss(res, sim$X, ini$kernel, start = 1, end = 200, select_p = 0.8)



```
